export enum socketEvents {
  INIT_ROOM = 'INIT_ROOM',
  ROOM_CREATED = 'ROOM_CREATED',
  INVALID_ROOM = 'INVALID_ROOM',
  JOIN_ROOM = 'JOIN_ROOM',
  UPDATE_PEERS = 'UPDATE_PEERS',
  LEAVE_ROOM = 'LEAVE_ROOM',
  CHECK_USERNAME = 'CHECK_USERNAME',
  USERNAME_VALID = 'USERNAME_VALID',
}
